#!/bin/bash
read -p "enter first number: " num1
read -p "enter second number: " num2
read -p "enter your choice[add/sub/mul/div]: " choice
case $choice in
add)
   
    sum=$(($num1+$num2))
    echo " sum is :$sum "
;;
sub)
 
    sub=$(($num1-$num2))
    echo " sub is :$sub "
;;
mul)
    mul=$(($num1*$num2))
    echo " mul is :$mul "
;;
div)
    div=$(($num1/$num2))
    echo " div is :$div "
;;
*)
   echo "sorry invalid input"
;;
esac



